name: Claude Code Integration

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then npm ci; fi
        if [ -f client/package.json ]; then cd client && npm ci && cd ..; fi
        
    - name: Run Claude Code
      uses: anthropics/claude-code-action@v1
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        timeout: 10m
        max-iterations: 5
        
    - name: Run tests (if available)
      run: |
        if [ -f package.json ] && grep -q '"test"' package.json; then npm test; fi
        if [ -f client/package.json ] && grep -q '"test"' client/package.json; then cd client && npm test && cd ..; fi
      continue-on-error: true